<?php
/**
 * MeetingLiveStream
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * MeetingLiveStream Class Doc Comment
 *
 * @category Class
 * @description Meeting Live Stream
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MeetingLiveStream implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MeetingLiveStream';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'stream_url' => 'string',
        'stream_key' => 'string',
        'page_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'stream_url' => null,
        'stream_key' => null,
        'page_url' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'stream_url' => 'stream_url',
        'stream_key' => 'stream_key',
        'page_url' => 'page_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'stream_url' => 'setStreamUrl',
        'stream_key' => 'setStreamKey',
        'page_url' => 'setPageUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'stream_url' => 'getStreamUrl',
        'stream_key' => 'getStreamKey',
        'page_url' => 'getPageUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['stream_url'] = isset($data['stream_url']) ? $data['stream_url'] : null;
        $this->container['stream_key'] = isset($data['stream_key']) ? $data['stream_key'] : null;
        $this->container['page_url'] = isset($data['page_url']) ? $data['page_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['stream_url'] === null) {
            $invalidProperties[] = "'stream_url' can't be null";
        }
        if ((mb_strlen($this->container['stream_url']) > 1024)) {
            $invalidProperties[] = "invalid value for 'stream_url', the character length must be smaller than or equal to 1024.";
        }

        if ($this->container['stream_key'] === null) {
            $invalidProperties[] = "'stream_key' can't be null";
        }
        if ((mb_strlen($this->container['stream_key']) > 512)) {
            $invalidProperties[] = "invalid value for 'stream_key', the character length must be smaller than or equal to 512.";
        }

        if (!is_null($this->container['page_url']) && (mb_strlen($this->container['page_url']) > 1024)) {
            $invalidProperties[] = "invalid value for 'page_url', the character length must be smaller than or equal to 1024.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets stream_url
     *
     * @return string
     */
    public function getStreamUrl()
    {
        return $this->container['stream_url'];
    }

    /**
     * Sets stream_url
     *
     * @param string $stream_url Server URL.
     *
     * @return $this
     */
    public function setStreamUrl($stream_url)
    {
        if ((mb_strlen($stream_url) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $stream_url when calling MeetingLiveStream., must be smaller than or equal to 1024.');
        }

        $this->container['stream_url'] = $stream_url;

        return $this;
    }

    /**
     * Gets stream_key
     *
     * @return string
     */
    public function getStreamKey()
    {
        return $this->container['stream_key'];
    }

    /**
     * Sets stream_key
     *
     * @param string $stream_key Stream name/key.
     *
     * @return $this
     */
    public function setStreamKey($stream_key)
    {
        if ((mb_strlen($stream_key) > 512)) {
            throw new \InvalidArgumentException('invalid length for $stream_key when calling MeetingLiveStream., must be smaller than or equal to 512.');
        }

        $this->container['stream_key'] = $stream_key;

        return $this;
    }

    /**
     * Gets page_url
     *
     * @return string
     */
    public function getPageUrl()
    {
        return $this->container['page_url'];
    }

    /**
     * Sets page_url
     *
     * @param string $page_url View URL.
     *
     * @return $this
     */
    public function setPageUrl($page_url)
    {
        if (!is_null($page_url) && (mb_strlen($page_url) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $page_url when calling MeetingLiveStream., must be smaller than or equal to 1024.');
        }

        $this->container['page_url'] = $page_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


