<?php
/**
 * QOSParticipantUserQos
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * QOSParticipantUserQos Class Doc Comment
 *
 * @category Class
 * @description User quality of service
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QOSParticipantUserQos implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'QOSParticipant_user_qos';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'date_time' => '\DateTime',
        'audio_input' => '\Swagger\Client\Model\QOSAudio',
        'audio_output' => '\Swagger\Client\Model\QOSAudio',
        'video_input' => '\Swagger\Client\Model\QOSVideo',
        'video_output' => '\Swagger\Client\Model\QOSVideo',
        'as_input' => '\Swagger\Client\Model\QOSVideo',
        'as_output' => '\Swagger\Client\Model\QOSVideo',
        'cpu_usage' => '\Swagger\Client\Model\QOSParticipantUserQosCpuUsage'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'date_time' => 'date-time',
        'audio_input' => null,
        'audio_output' => null,
        'video_input' => null,
        'video_output' => null,
        'as_input' => null,
        'as_output' => null,
        'cpu_usage' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date_time' => 'date_time',
        'audio_input' => 'audio_input',
        'audio_output' => 'audio_output',
        'video_input' => 'video_input',
        'video_output' => 'video_output',
        'as_input' => 'as_input',
        'as_output' => 'as_output',
        'cpu_usage' => 'cpu_usage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date_time' => 'setDateTime',
        'audio_input' => 'setAudioInput',
        'audio_output' => 'setAudioOutput',
        'video_input' => 'setVideoInput',
        'video_output' => 'setVideoOutput',
        'as_input' => 'setAsInput',
        'as_output' => 'setAsOutput',
        'cpu_usage' => 'setCpuUsage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date_time' => 'getDateTime',
        'audio_input' => 'getAudioInput',
        'audio_output' => 'getAudioOutput',
        'video_input' => 'getVideoInput',
        'video_output' => 'getVideoOutput',
        'as_input' => 'getAsInput',
        'as_output' => 'getAsOutput',
        'cpu_usage' => 'getCpuUsage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['date_time'] = isset($data['date_time']) ? $data['date_time'] : null;
        $this->container['audio_input'] = isset($data['audio_input']) ? $data['audio_input'] : null;
        $this->container['audio_output'] = isset($data['audio_output']) ? $data['audio_output'] : null;
        $this->container['video_input'] = isset($data['video_input']) ? $data['video_input'] : null;
        $this->container['video_output'] = isset($data['video_output']) ? $data['video_output'] : null;
        $this->container['as_input'] = isset($data['as_input']) ? $data['as_input'] : null;
        $this->container['as_output'] = isset($data['as_output']) ? $data['as_output'] : null;
        $this->container['cpu_usage'] = isset($data['cpu_usage']) ? $data['cpu_usage'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date_time
     *
     * @return \DateTime
     */
    public function getDateTime()
    {
        return $this->container['date_time'];
    }

    /**
     * Sets date_time
     *
     * @param \DateTime $date_time Datetime of QOS
     *
     * @return $this
     */
    public function setDateTime($date_time)
    {
        $this->container['date_time'] = $date_time;

        return $this;
    }

    /**
     * Gets audio_input
     *
     * @return \Swagger\Client\Model\QOSAudio
     */
    public function getAudioInput()
    {
        return $this->container['audio_input'];
    }

    /**
     * Sets audio_input
     *
     * @param \Swagger\Client\Model\QOSAudio $audio_input audio_input
     *
     * @return $this
     */
    public function setAudioInput($audio_input)
    {
        $this->container['audio_input'] = $audio_input;

        return $this;
    }

    /**
     * Gets audio_output
     *
     * @return \Swagger\Client\Model\QOSAudio
     */
    public function getAudioOutput()
    {
        return $this->container['audio_output'];
    }

    /**
     * Sets audio_output
     *
     * @param \Swagger\Client\Model\QOSAudio $audio_output audio_output
     *
     * @return $this
     */
    public function setAudioOutput($audio_output)
    {
        $this->container['audio_output'] = $audio_output;

        return $this;
    }

    /**
     * Gets video_input
     *
     * @return \Swagger\Client\Model\QOSVideo
     */
    public function getVideoInput()
    {
        return $this->container['video_input'];
    }

    /**
     * Sets video_input
     *
     * @param \Swagger\Client\Model\QOSVideo $video_input video_input
     *
     * @return $this
     */
    public function setVideoInput($video_input)
    {
        $this->container['video_input'] = $video_input;

        return $this;
    }

    /**
     * Gets video_output
     *
     * @return \Swagger\Client\Model\QOSVideo
     */
    public function getVideoOutput()
    {
        return $this->container['video_output'];
    }

    /**
     * Sets video_output
     *
     * @param \Swagger\Client\Model\QOSVideo $video_output video_output
     *
     * @return $this
     */
    public function setVideoOutput($video_output)
    {
        $this->container['video_output'] = $video_output;

        return $this;
    }

    /**
     * Gets as_input
     *
     * @return \Swagger\Client\Model\QOSVideo
     */
    public function getAsInput()
    {
        return $this->container['as_input'];
    }

    /**
     * Sets as_input
     *
     * @param \Swagger\Client\Model\QOSVideo $as_input as_input
     *
     * @return $this
     */
    public function setAsInput($as_input)
    {
        $this->container['as_input'] = $as_input;

        return $this;
    }

    /**
     * Gets as_output
     *
     * @return \Swagger\Client\Model\QOSVideo
     */
    public function getAsOutput()
    {
        return $this->container['as_output'];
    }

    /**
     * Sets as_output
     *
     * @param \Swagger\Client\Model\QOSVideo $as_output as_output
     *
     * @return $this
     */
    public function setAsOutput($as_output)
    {
        $this->container['as_output'] = $as_output;

        return $this;
    }

    /**
     * Gets cpu_usage
     *
     * @return \Swagger\Client\Model\QOSParticipantUserQosCpuUsage
     */
    public function getCpuUsage()
    {
        return $this->container['cpu_usage'];
    }

    /**
     * Sets cpu_usage
     *
     * @param \Swagger\Client\Model\QOSParticipantUserQosCpuUsage $cpu_usage cpu_usage
     *
     * @return $this
     */
    public function setCpuUsage($cpu_usage)
    {
        $this->container['cpu_usage'] = $cpu_usage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


