<?php
/**
 * AccountSettingsScheduleMeetingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountSettingsScheduleMeetingTest Class Doc Comment
 *
 * @category    Class
 * @description Account Settings: Schedule Meeting
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountSettingsScheduleMeetingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountSettingsScheduleMeeting"
     */
    public function testAccountSettingsScheduleMeeting()
    {
    }

    /**
     * Test attribute "host_video"
     */
    public function testPropertyHostVideo()
    {
    }

    /**
     * Test attribute "participant_video"
     */
    public function testPropertyParticipantVideo()
    {
    }

    /**
     * Test attribute "audio_type"
     */
    public function testPropertyAudioType()
    {
    }

    /**
     * Test attribute "join_before_host"
     */
    public function testPropertyJoinBeforeHost()
    {
    }

    /**
     * Test attribute "enforce_login"
     */
    public function testPropertyEnforceLogin()
    {
    }

    /**
     * Test attribute "enforce_login_with_domains"
     */
    public function testPropertyEnforceLoginWithDomains()
    {
    }

    /**
     * Test attribute "enforce_login_domains"
     */
    public function testPropertyEnforceLoginDomains()
    {
    }

    /**
     * Test attribute "not_store_meeting_topic"
     */
    public function testPropertyNotStoreMeetingTopic()
    {
    }

    /**
     * Test attribute "force_pmi_jbh_password"
     */
    public function testPropertyForcePmiJbhPassword()
    {
    }
}
