<?php
/**
 * AccountPlansTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountPlansTest Class Doc Comment
 *
 * @category    Class
 * @description Account Plans object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountPlansTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountPlans"
     */
    public function testAccountPlans()
    {
    }

    /**
     * Test attribute "plan_base"
     */
    public function testPropertyPlanBase()
    {
    }

    /**
     * Test attribute "plan_zoom_rooms"
     */
    public function testPropertyPlanZoomRooms()
    {
    }

    /**
     * Test attribute "plan_room_connector"
     */
    public function testPropertyPlanRoomConnector()
    {
    }

    /**
     * Test attribute "plan_large_meeting"
     */
    public function testPropertyPlanLargeMeeting()
    {
    }

    /**
     * Test attribute "plan_webinar"
     */
    public function testPropertyPlanWebinar()
    {
    }

    /**
     * Test attribute "plan_recording"
     */
    public function testPropertyPlanRecording()
    {
    }

    /**
     * Test attribute "plan_audio"
     */
    public function testPropertyPlanAudio()
    {
    }
}
