<?php
/**
 * AccountSettingsRecordingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountSettingsRecordingTest Class Doc Comment
 *
 * @category    Class
 * @description Account Settings: Recording
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountSettingsRecordingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountSettingsRecording"
     */
    public function testAccountSettingsRecording()
    {
    }

    /**
     * Test attribute "local_recording"
     */
    public function testPropertyLocalRecording()
    {
    }

    /**
     * Test attribute "cloud_recording"
     */
    public function testPropertyCloudRecording()
    {
    }

    /**
     * Test attribute "record_speaker_view"
     */
    public function testPropertyRecordSpeakerView()
    {
    }

    /**
     * Test attribute "record_gallery_view"
     */
    public function testPropertyRecordGalleryView()
    {
    }

    /**
     * Test attribute "record_audio_file"
     */
    public function testPropertyRecordAudioFile()
    {
    }

    /**
     * Test attribute "save_chat_text"
     */
    public function testPropertySaveChatText()
    {
    }

    /**
     * Test attribute "show_timestamp"
     */
    public function testPropertyShowTimestamp()
    {
    }

    /**
     * Test attribute "recording_audio_transcript"
     */
    public function testPropertyRecordingAudioTranscript()
    {
    }

    /**
     * Test attribute "auto_recording"
     */
    public function testPropertyAutoRecording()
    {
    }

    /**
     * Test attribute "cloud_recording_download"
     */
    public function testPropertyCloudRecordingDownload()
    {
    }

    /**
     * Test attribute "cloud_recording_download_host"
     */
    public function testPropertyCloudRecordingDownloadHost()
    {
    }

    /**
     * Test attribute "account_user_access_recording"
     */
    public function testPropertyAccountUserAccessRecording()
    {
    }

    /**
     * Test attribute "auto_delete_cmr"
     */
    public function testPropertyAutoDeleteCmr()
    {
    }

    /**
     * Test attribute "auto_delete_cmr_days"
     */
    public function testPropertyAutoDeleteCmrDays()
    {
    }
}
