<?php
/**
 * AccountSettingsSecurityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountSettingsSecurityTest Class Doc Comment
 *
 * @category    Class
 * @description Account Settings: Security
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountSettingsSecurityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountSettingsSecurity"
     */
    public function testAccountSettingsSecurity()
    {
    }

    /**
     * Test attribute "admin_change_name_pic"
     */
    public function testPropertyAdminChangeNamePic()
    {
    }

    /**
     * Test attribute "import_photos_from_devices"
     */
    public function testPropertyImportPhotosFromDevices()
    {
    }

    /**
     * Test attribute "hide_billing_info"
     */
    public function testPropertyHideBillingInfo()
    {
    }
}
