<?php
/**
 * PACTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PACTest Class Doc Comment
 *
 * @category    Class
 * @description List of PAC Accounts
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PACTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PAC"
     */
    public function testPAC()
    {
    }

    /**
     * Test attribute "dedicated_dial_in_number"
     */
    public function testPropertyDedicatedDialInNumber()
    {
    }

    /**
     * Test attribute "global_dial_in_numbers"
     */
    public function testPropertyGlobalDialInNumbers()
    {
    }

    /**
     * Test attribute "conference_id"
     */
    public function testPropertyConferenceId()
    {
    }

    /**
     * Test attribute "participant_password"
     */
    public function testPropertyParticipantPassword()
    {
    }

    /**
     * Test attribute "listen_only_password"
     */
    public function testPropertyListenOnlyPassword()
    {
    }
}
