<?php
/**
 * QOSAudioTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QOSAudioTest Class Doc Comment
 *
 * @category    Class
 * @description Quality of Service object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QOSAudioTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QOSAudio"
     */
    public function testQOSAudio()
    {
    }

    /**
     * Test attribute "bitrate"
     */
    public function testPropertyBitrate()
    {
    }

    /**
     * Test attribute "latency"
     */
    public function testPropertyLatency()
    {
    }

    /**
     * Test attribute "jitter"
     */
    public function testPropertyJitter()
    {
    }

    /**
     * Test attribute "avg_loss"
     */
    public function testPropertyAvgLoss()
    {
    }

    /**
     * Test attribute "max_loss"
     */
    public function testPropertyMaxLoss()
    {
    }
}
