<?php
/**
 * QOSParticipantUserQosTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QOSParticipantUserQosTest Class Doc Comment
 *
 * @category    Class
 * @description User quality of service
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QOSParticipantUserQosTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QOSParticipantUserQos"
     */
    public function testQOSParticipantUserQos()
    {
    }

    /**
     * Test attribute "date_time"
     */
    public function testPropertyDateTime()
    {
    }

    /**
     * Test attribute "audio_input"
     */
    public function testPropertyAudioInput()
    {
    }

    /**
     * Test attribute "audio_output"
     */
    public function testPropertyAudioOutput()
    {
    }

    /**
     * Test attribute "video_input"
     */
    public function testPropertyVideoInput()
    {
    }

    /**
     * Test attribute "video_output"
     */
    public function testPropertyVideoOutput()
    {
    }

    /**
     * Test attribute "as_input"
     */
    public function testPropertyAsInput()
    {
    }

    /**
     * Test attribute "as_output"
     */
    public function testPropertyAsOutput()
    {
    }

    /**
     * Test attribute "cpu_usage"
     */
    public function testPropertyCpuUsage()
    {
    }
}
