<?php
/**
 * QOSParticipantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QOSParticipantTest Class Doc Comment
 *
 * @category    Class
 * @description Participant QOS
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QOSParticipantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QOSParticipant"
     */
    public function testQOSParticipant()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "user_name"
     */
    public function testPropertyUserName()
    {
    }

    /**
     * Test attribute "device"
     */
    public function testPropertyDevice()
    {
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "join_time"
     */
    public function testPropertyJoinTime()
    {
    }

    /**
     * Test attribute "leave_time"
     */
    public function testPropertyLeaveTime()
    {
    }

    /**
     * Test attribute "pc_name"
     */
    public function testPropertyPcName()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "mac_addr"
     */
    public function testPropertyMacAddr()
    {
    }

    /**
     * Test attribute "harddisk_id"
     */
    public function testPropertyHarddiskId()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "user_qos"
     */
    public function testPropertyUserQos()
    {
    }
}
