<?php
/**
 * RecordingSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RecordingSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description RecordingSettings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecordingSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RecordingSettings"
     */
    public function testRecordingSettings()
    {
    }

    /**
     * Test attribute "share_recording"
     */
    public function testPropertyShareRecording()
    {
    }

    /**
     * Test attribute "viewer_download"
     */
    public function testPropertyViewerDownload()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "on_demand"
     */
    public function testPropertyOnDemand()
    {
    }

    /**
     * Test attribute "approval_type"
     */
    public function testPropertyApprovalType()
    {
    }

    /**
     * Test attribute "send_email_to_host"
     */
    public function testPropertySendEmailToHost()
    {
    }

    /**
     * Test attribute "show_social_share_buttons"
     */
    public function testPropertyShowSocialShareButtons()
    {
    }
}
