<?php
/**
 * RecordingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RecordingTest Class Doc Comment
 *
 * @category    Class
 * @description Recording file Object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecordingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Recording"
     */
    public function testRecording()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "meeting_id"
     */
    public function testPropertyMeetingId()
    {
    }

    /**
     * Test attribute "recording_start"
     */
    public function testPropertyRecordingStart()
    {
    }

    /**
     * Test attribute "recording_end"
     */
    public function testPropertyRecordingEnd()
    {
    }

    /**
     * Test attribute "file_type"
     */
    public function testPropertyFileType()
    {
    }

    /**
     * Test attribute "file_size"
     */
    public function testPropertyFileSize()
    {
    }

    /**
     * Test attribute "play_url"
     */
    public function testPropertyPlayUrl()
    {
    }

    /**
     * Test attribute "download_url"
     */
    public function testPropertyDownloadUrl()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "deleted_time"
     */
    public function testPropertyDeletedTime()
    {
    }

    /**
     * Test attribute "recording_type"
     */
    public function testPropertyRecordingType()
    {
    }
}
