<?php
/**
 * RecurrenceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RecurrenceTest Class Doc Comment
 *
 * @category    Class
 * @description Recurrence object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecurrenceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Recurrence"
     */
    public function testRecurrence()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "repeat_interval"
     */
    public function testPropertyRepeatInterval()
    {
    }

    /**
     * Test attribute "weekly_days"
     */
    public function testPropertyWeeklyDays()
    {
    }

    /**
     * Test attribute "monthly_day"
     */
    public function testPropertyMonthlyDay()
    {
    }

    /**
     * Test attribute "monthly_week"
     */
    public function testPropertyMonthlyWeek()
    {
    }

    /**
     * Test attribute "monthly_week_day"
     */
    public function testPropertyMonthlyWeekDay()
    {
    }

    /**
     * Test attribute "end_times"
     */
    public function testPropertyEndTimes()
    {
    }

    /**
     * Test attribute "end_date_time"
     */
    public function testPropertyEndDateTime()
    {
    }
}
