<?php
/**
 * RegistrantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RegistrantTest Class Doc Comment
 *
 * @category    Class
 * @description Registrant base object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RegistrantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Registrant"
     */
    public function testRegistrant()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "industry"
     */
    public function testPropertyIndustry()
    {
    }

    /**
     * Test attribute "org"
     */
    public function testPropertyOrg()
    {
    }

    /**
     * Test attribute "job_title"
     */
    public function testPropertyJobTitle()
    {
    }

    /**
     * Test attribute "purchasing_time_frame"
     */
    public function testPropertyPurchasingTimeFrame()
    {
    }

    /**
     * Test attribute "role_in_purchase_process"
     */
    public function testPropertyRoleInPurchaseProcess()
    {
    }

    /**
     * Test attribute "no_of_employees"
     */
    public function testPropertyNoOfEmployees()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "custom_questions"
     */
    public function testPropertyCustomQuestions()
    {
    }
}
