<?php
/**
 * UserSettingsScheduleMeetingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserSettingsScheduleMeetingTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserSettingsScheduleMeetingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserSettingsScheduleMeeting"
     */
    public function testUserSettingsScheduleMeeting()
    {
    }

    /**
     * Test attribute "host_video"
     */
    public function testPropertyHostVideo()
    {
    }

    /**
     * Test attribute "participants_video"
     */
    public function testPropertyParticipantsVideo()
    {
    }

    /**
     * Test attribute "audio_type"
     */
    public function testPropertyAudioType()
    {
    }

    /**
     * Test attribute "join_before_host"
     */
    public function testPropertyJoinBeforeHost()
    {
    }

    /**
     * Test attribute "force_pmi_jbh_password"
     */
    public function testPropertyForcePmiJbhPassword()
    {
    }

    /**
     * Test attribute "pstn_password_protected"
     */
    public function testPropertyPstnPasswordProtected()
    {
    }
}
