<?php
/**
 * UserSettingsFeatureUpdateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserSettingsFeatureUpdateTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserSettingsFeatureUpdateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserSettingsFeatureUpdate"
     */
    public function testUserSettingsFeatureUpdate()
    {
    }

    /**
     * Test attribute "meeting_capacity"
     */
    public function testPropertyMeetingCapacity()
    {
    }

    /**
     * Test attribute "large_meeting"
     */
    public function testPropertyLargeMeeting()
    {
    }

    /**
     * Test attribute "large_meeting_capacity"
     */
    public function testPropertyLargeMeetingCapacity()
    {
    }

    /**
     * Test attribute "webinar"
     */
    public function testPropertyWebinar()
    {
    }

    /**
     * Test attribute "webinar_capacity"
     */
    public function testPropertyWebinarCapacity()
    {
    }
}
