<?php
/**
 * WebinarMetricTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WebinarMetricTest Class Doc Comment
 *
 * @category    Class
 * @description Webinar metric details
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebinarMetricTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WebinarMetric"
     */
    public function testWebinarMetric()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "topic"
     */
    public function testPropertyTopic()
    {
    }

    /**
     * Test attribute "host"
     */
    public function testPropertyHost()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "user_type"
     */
    public function testPropertyUserType()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "participants"
     */
    public function testPropertyParticipants()
    {
    }

    /**
     * Test attribute "has_pstn"
     */
    public function testPropertyHasPstn()
    {
    }

    /**
     * Test attribute "has_voip"
     */
    public function testPropertyHasVoip()
    {
    }

    /**
     * Test attribute "has_3rd_party_audio"
     */
    public function testPropertyHas3rdPartyAudio()
    {
    }

    /**
     * Test attribute "has_video"
     */
    public function testPropertyHasVideo()
    {
    }

    /**
     * Test attribute "has_screen_share"
     */
    public function testPropertyHasScreenShare()
    {
    }

    /**
     * Test attribute "has_recording"
     */
    public function testPropertyHasRecording()
    {
    }

    /**
     * Test attribute "has_sip"
     */
    public function testPropertyHasSip()
    {
    }
}
