<?php
/**
 * BillingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BillingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BillingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountBilling
     *
     * Retrieve billing information for a sub account.
     *
     */
    public function testAccountBilling()
    {
    }

    /**
     * Test case for accountBillingUpdate
     *
     * Update billing information for a sub account.
     *
     */
    public function testAccountBillingUpdate()
    {
    }

    /**
     * Test case for accountPlanAddonCreate
     *
     * Add an additional plan for sub account.
     *
     */
    public function testAccountPlanAddonCreate()
    {
    }

    /**
     * Test case for accountPlanAddonUpdate
     *
     * Update an additional plan for sub account.
     *
     */
    public function testAccountPlanAddonUpdate()
    {
    }

    /**
     * Test case for accountPlanBaseUpdate
     *
     * Update a base plan for a sub account.
     *
     */
    public function testAccountPlanBaseUpdate()
    {
    }

    /**
     * Test case for accountPlanCreate
     *
     * Subscribe plans for a sub account.
     *
     */
    public function testAccountPlanCreate()
    {
    }

    /**
     * Test case for accountPlans
     *
     * Retrieve plan information for a sub account.
     *
     */
    public function testAccountPlans()
    {
    }
}
