<?php
/**
 * DashboardsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DashboardsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DashboardsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dashboardCRC
     *
     * Retrieve CRC Port Usage.
     *
     */
    public function testDashboardCRC()
    {
    }

    /**
     * Test case for dashboardIM
     *
     * Retrieve IM.
     *
     */
    public function testDashboardIM()
    {
    }

    /**
     * Test case for dashboardMeetingDetail
     *
     * Retrieve meeting detail.
     *
     */
    public function testDashboardMeetingDetail()
    {
    }

    /**
     * Test case for dashboardMeetingParticipantQOS
     *
     * Retrieve meeting participant QOS.
     *
     */
    public function testDashboardMeetingParticipantQOS()
    {
    }

    /**
     * Test case for dashboardMeetingParticipantShare
     *
     * Retrieve sharing/recording details of meeting participant.
     *
     */
    public function testDashboardMeetingParticipantShare()
    {
    }

    /**
     * Test case for dashboardMeetingParticipants
     *
     * Retrieve meeting participants.
     *
     */
    public function testDashboardMeetingParticipants()
    {
    }

    /**
     * Test case for dashboardMeetingParticipantsQOS
     *
     * List meeting participants QOS.
     *
     */
    public function testDashboardMeetingParticipantsQOS()
    {
    }

    /**
     * Test case for dashboardMeetings
     *
     * List meetings.
     *
     */
    public function testDashboardMeetings()
    {
    }

    /**
     * Test case for dashboardWebinarDetail
     *
     * Retrieve webinar detail.
     *
     */
    public function testDashboardWebinarDetail()
    {
    }

    /**
     * Test case for dashboardWebinarParticipantQOS
     *
     * Retrieve webinar participant QOS.
     *
     */
    public function testDashboardWebinarParticipantQOS()
    {
    }

    /**
     * Test case for dashboardWebinarParticipantShare
     *
     * Retrieve sharing/recording details of webinar participant.
     *
     */
    public function testDashboardWebinarParticipantShare()
    {
    }

    /**
     * Test case for dashboardWebinarParticipants
     *
     * Retrieve webinar participants.
     *
     */
    public function testDashboardWebinarParticipants()
    {
    }

    /**
     * Test case for dashboardWebinarParticipantsQOS
     *
     * List webinar participant QOS.
     *
     */
    public function testDashboardWebinarParticipantsQOS()
    {
    }

    /**
     * Test case for dashboardWebinars
     *
     * List webinars.
     *
     */
    public function testDashboardWebinars()
    {
    }

    /**
     * Test case for dashboardZoomRoom
     *
     * Retrieve Zoom Room.
     *
     */
    public function testDashboardZoomRoom()
    {
    }

    /**
     * Test case for dashboardZoomRooms
     *
     * List Zoom Rooms.
     *
     */
    public function testDashboardZoomRooms()
    {
    }
}
