<?php
/**
 * IMGroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * IMGroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IMGroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for imGroup
     *
     * Retrieve an IM Group.
     *
     */
    public function testImGroup()
    {
    }

    /**
     * Test case for imGroupCreate
     *
     * Create an IM Group.
     *
     */
    public function testImGroupCreate()
    {
    }

    /**
     * Test case for imGroupDelete
     *
     * Delete an IM Group.
     *
     */
    public function testImGroupDelete()
    {
    }

    /**
     * Test case for imGroupMembers
     *
     * List an IM Group's members.
     *
     */
    public function testImGroupMembers()
    {
    }

    /**
     * Test case for imGroupMembersCreate
     *
     * Add IM Group members.
     *
     */
    public function testImGroupMembersCreate()
    {
    }

    /**
     * Test case for imGroupMembersDelete
     *
     * Delete an IM Group member.
     *
     */
    public function testImGroupMembersDelete()
    {
    }

    /**
     * Test case for imGroupUpdate
     *
     * Update an IM Group.
     *
     */
    public function testImGroupUpdate()
    {
    }

    /**
     * Test case for imGroups
     *
     * List IM Groups.
     *
     */
    public function testImGroups()
    {
    }
}
