<?php
/**
 * TrackingFieldApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Zoom API
 *
 * API Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: developer@zoom.us
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TrackingFieldApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TrackingFieldApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for trackingfieldCreate
     *
     * Create a Tracking Field.
     *
     */
    public function testTrackingfieldCreate()
    {
    }

    /**
     * Test case for trackingfieldDelete
     *
     * Delete a Tracking Field.
     *
     */
    public function testTrackingfieldDelete()
    {
    }

    /**
     * Test case for trackingfieldGet
     *
     * Retrieve a tracking field.
     *
     */
    public function testTrackingfieldGet()
    {
    }

    /**
     * Test case for trackingfieldList
     *
     * List Tracking Fields..
     *
     */
    public function testTrackingfieldList()
    {
    }

    /**
     * Test case for trackingfieldUpdate
     *
     * Update a Tracking Field.
     *
     */
    public function testTrackingfieldUpdate()
    {
    }
}
